### ISSUE TITLE
Radio buttons/checkboxes don't have pressed state

### ISSUE THREAD

**Issue by jrgp** [jdan/98.css#11]
To closer mimic the original, when clicking and holding these controls, they should be displayed differently. IIRC Windows changes the white background to gray.

**Comment by CaptainFalcon92** [comment]
Could you provide a reference picture here please ?
I'm willing to give it a try myself, or for anyone that would like to.

**Comment by jrgp** [comment]
Hey, here's what it looks like if you click and hold with the current state being checked:

![98 down](https://user-images.githubusercontent.com/472066/80267351-2176d700-8655-11ea-8eda-9f5b1354df76.png)

**Comment by jdan** [comment]
Fixed via #63 (thanks @cassiohub 😍)
