### ISSUE TITLE
Status Bar not working in Unpkg

### ISSUE THREAD

**Issue by metropolis-nostalgia** [jdan/98.css#112]
I recently build a html file with your CSS code from Unpkg. But the status bar (`status-bar` class) is not working. Here are screenshot of that: 
![98notworking](https://user-images.githubusercontent.com/82685767/115096131-ed459780-9ef1-11eb-9680-005eef7309a7.png).
While the status bar works in other theme. Screenshot from Botoxparty's XP.css:
![XPstatusbar](https://user-images.githubusercontent.com/82685767/115096209-24b44400-9ef2-11eb-9b4a-9cb5823bf080.png)
And Khang-nd's 7.css:
![7statusbar](https://user-images.githubusercontent.com/82685767/115096241-46153000-9ef2-11eb-9b28-1b902559181f.png)
I tried to search for the CSS code for `status-bar` class in Unpkg but it don't show any result. But I found that code in `style.css`, in your main repo!
I think the unpkg repo need to be update.

**Comment by genz-finance** [comment]
Also seeing this. Ended up just copying the following classes into my `styles.css` as a temporary workaround 

```

.status-bar {
  margin: 0px 1px;
  display: flex;
  gap: 1px;
}

.status-bar-field {
  box-shadow: inset -1px -1px  #dfdfdf, 
    inset 1px 1px #808080;
  flex-grow: 1;
  padding: 2px 3px;
  margin: 0;
}

```

**Comment by jdan** [comment]
Sorry about that! Just pushed 0.1.17 :)
