### ISSUE TITLE
Add an icon/image next to an item in a tree?

### ISSUE THREAD

**Issue by Nasko-5** [jdan/98.css#116]
More of a question/suggestion than an issue, but.
I was wondering if there was a way to put an icon/image next to an item in a tree?
Something like the file tree in thee win98 explorer:
![Screenshot_5](https://user-images.githubusercontent.com/66528033/120887334-d589b600-c5fa-11eb-9cd6-714030143f68.png)

If not, would it be possible to implement? And how?

**Comment by Sabinno** [comment]
Is this not already possible? Have you tried adding an image within a list item yourself?

**Comment by jdan** [comment]
You should be able to with just an img tag and some positioning! Let us know if you run into any issues though.
