### ISSUE TITLE
Windows 98 tooltips

### ISSUE THREAD

**Issue by abacef** [jdan/98.css#121]
Would you be able to support adding Windows 98 style tooltips to things? I am pretty sure the OS had them right?

**Comment by its-pablo** [comment]
+1 to this! 7.css has this - https://khang-nd.github.io/7.css/#balloon

**Comment by hollowmage** [comment]
To be honest, I don't think it did, no. Balloon messages pointing at system tray icons only started being a thing in Windows XP.

**Comment by juanigaray** [comment]
Closing as off-scope -- If you think this is a mistake, let me know!
