### ISSUE TITLE
Title bar icons not showing when using local version?

### ISSUE THREAD

**Issue by googleooer** [jdan/98.css#134]
![report1](https://user-images.githubusercontent.com/35429559/169631418-d081ea67-ad48-453b-a4f3-63604996f2ad.png)
![report2](https://user-images.githubusercontent.com/35429559/169631419-56732e05-7923-4092-9d9b-f9da9d64535b.png)

**Comment by googleooer** [comment]
Does not happen if I use the unpkg version, but I don't want my project to require internet access

**Comment by isiah-lloyd** [comment]
I'm using 98.css locally and those icon appear fine for me. How did you install locally? The recommended way is through npm. 

When you look at the elements in the developer tools can you see what style is applied to them? It should look something like this: 
![image](https://user-images.githubusercontent.com/885544/169667158-c4eb0c71-6ab7-464b-918f-35dbe1216dc1.png)

**Comment by isiah-lloyd** [comment]
Also, this previous discussion may help with your issue: https://github.com/jdan/98.css/discussions/113

**Comment by googleooer** [comment]
It doesn't seem to want to load the icons?
![report4](https://user-images.githubusercontent.com/35429559/169667240-264e6b50-65b9-47cf-867c-b8cfdfa4e0b2.png)

**Comment by googleooer** [comment]
oh nevermind i have to use the one from the dist folder
