### ISSUE TITLE
Add Github Action to publish new releases to npm

### ISSUE THREAD

**Issue by isiah-lloyd** [jdan/98.css#135]
@jdan I could create this workflow if you add a [npm token](https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-tokens-on-the-website) to the [repositories secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

I'd create a workflow following [this](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry ) example.

**Comment by jdan** [comment]
Done! Added `NPM_TOKEN`

**Comment by isiah-lloyd** [comment]
@jdan I'm not sure if I created the action wrong or maybe I don't have the required permissions to actually make actions but I created a release and it didn't run. It would be appreciated if you could publish to npm or maybe force a run of the action to see if it works. 

Thanks!

**Comment by jdan** [comment]
@isiah-lloyd Let's give it a whirl! I changed `created` to `published` as it seems like `created` might only be for drafts?? or some weird webhook thing. not a clue.

I also added `workflow_dispatch` so we can manually do it.

https://github.com/jdan/98.css/actions/runs/2366615860

**Comment by jdan** [comment]
Huzzah! 

![image](https://user-images.githubusercontent.com/287268/169698316-b66f7b4a-a3cb-40ed-aca4-39c3342fa98b.png)

Had to fiddle with my token to bypass 2FA, apologies for email spam. Thanks for setting this up, very cool
