### ISSUE TITLE
Checkbox cannot center check mark

### ISSUE THREAD

**Issue by metropolis-nostalgia** [jdan/98.css#142]
### Description
Somehow if the label is wrapped into more than one line, the checkbox will be centered, but the check mark (✓) is still not centered, which leave this error:
![Checkmark error](https://user-images.githubusercontent.com/82685767/193435445-fd39c793-1e69-4eed-98a5-9005f9933629.png)
Instead of this:
![desirable](https://user-images.githubusercontent.com/82685767/193435519-7767d1b5-95ed-404f-a649-86154e2cd7f7.png)
### How to reproduce
The label have to be warped into more than one line.

**Comment by vtlanglois** [comment]
Tested this on Safari on MacOS and Chrome on Windows, could not find any visual changes in the position when `top: ...` was removed. Taking this bug and putting up a PR to fix this
