### ISSUE TITLE
Pressing on the npm link on the website pops a save password prompt

### ISSUE THREAD

**Issue by arye321** [jdan/98.css#149]
![image](https://user-images.githubusercontent.com/9559551/197654983-6b4f8945-c42e-4574-99bb-db6b2967059e.png)

![image](https://user-images.githubusercontent.com/9559551/197654602-b8537d28-3baa-4c0d-a3e1-60f8c234b187.png)

I assume it has something to do with this

![image](https://user-images.githubusercontent.com/9559551/197655080-5ab3c53e-32ae-43f3-9c4d-f4b6a211acaa.png)

this is on Windows 10, Firefox 105.0.3 (64-bit)

**Comment by KontrollFreek** [comment]
Not really an issue, this behavior is set by your web browser and always happens when entering a new page on one with a filled in (assumed) username and password
