### ISSUE TITLE
Missing scrollbars (proposal inside)

### ISSUE THREAD

**Issue by BeardedBear** [jdan/98.css#16]
Hi !!! 

I noticed that the scrollbars were missing, I played a bit on CodePen to try to reproduce them, and I came up with this result: https://codepen.io/BeardedBear/pen/jObVXmV

![image](https://user-images.githubusercontent.com/7188702/79989312-fbfc9880-84af-11ea-91e3-8c582da93e1a.png)

Are you interested? Feel free to retrieve the code if you are :)

however, I never found solutions for Firefox :(

Edit note : Thanks padraigfl for the button trick.

**Comment by padraigfl** [comment]
Feel free to use mine: https://github.com/padraigfl/packard-belle/blob/master/src/_scss/w98/theme.scss 

It's a chrome only fix, mind

![Screenshot 2020-04-22 at 12 51 44](https://user-images.githubusercontent.com/14135877/79978601-14f94f80-8498-11ea-8e97-441f941dfa32.png)

**Comment by BeardedBear** [comment]
@padraigfl yours is really great!

**Comment by BeardedBear** [comment]
@padraigfl I didn't know that ` :start:decrement`,  and `:horizontal:decrement` (and the others) existed! Thanks for the tip! I took the liberty of updating my Pen with it!

**Comment by jdan** [comment]
Hey both :) I include these https://github.com/jdan/98.css/blob/32b8da0ae2458a853d708229f1eb3792f768df29/style.css#L445-L480, are they not showing up for you? They show up on my desktop Chrome but it's quite possible I messed something up.

**Comment by davwheat** [comment]
They appear fine for me (Chrome 81, Windows 10)

**Comment by padraigfl** [comment]
I didn't actually check 😬 
Looking now the bars are there but the buttons aren't, however it works across browsers much better going on a quick comparison there now

**Comment by AdrianoCahete** [comment]
I have a customization for Firefox scrollbar on my portfolio, but I don't know if it will work for that type of customization: https://github.com/AdrianoCahete/adrianocahete.dev/blob/master/assets/styles/base.styl#L75

**Comment by jdan** [comment]
@padraigfl @BeardedBear could you let me know what browsers you're both using and if this is still an issue?

**Comment by padraigfl** [comment]
the buttons are appearing for me now, all looks good!
