### ISSUE TITLE
I can't change scrollbar button

### ISSUE THREAD

**Issue by Azoart** [jdan/98.css#162]
Hello! I created a GitHub account just to ask for help with this.

I'm trying to change the color of the scrollbar buttons & of the table header. This is the CSS code i added (i linked the upkmg-something CSS and this custom CSS that i made to change the colors of a few things):
`th,
thead {
  background-color:#99B2BF;
}`
`::-webkit-scrollbar-button {
  background-color:#99B2BF;
}`

Please forgive me if i didn't type in anything right, this is my first time using GitHub and as i said i just created a account to ask for help with this. I'm not sure if it's necessarily a issue with the CSS, it's probably just because I'm not that good with CSS.

**Comment by juanigaray** [comment]
This project simply provides a stylesheet, which you can read to find out how it manages to style the different elements of your web page. I'll close this issue, as it doesn't represent an issue with 98.css.

With that said, my best guess is your selectors aren't [specific](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) enough, and therefore the 98.css styles are the ones applied.

I recommend reading about specificity and child combinators, and if you encounter further problems to ask for assistance in help forums.
