### ISSUE TITLE
Not really an issue but how to center text?

### ISSUE THREAD

**Issue by xx1182** [jdan/98.css#168]
Take this exemple:
```
        <div class="title-bar" style="height: 100px;">
            <div class="title-bar-text" style="text-align: center;">bad words</div>
          </div>
```

![image](https://github.com/jdan/98.css/assets/6748908/253cdad6-5a48-49c5-9ee0-d35436c8b523)

regards.

**Comment by TheVikJ** [comment]
Hey! It's possible that the width of the parent div or title-bar-text might be set to fit the content (the text within). 

Have you tried setting the width of the divs to something like 100vw?

**Comment by juanigaray** [comment]
Hey @xx1182, this is the comment I left on the PR that's linked to this issue. I was wondering if you could help figure out whether this is in-scope for this repo.

`Hi! I'm wondering if there's a precedent for centered text in Windows 98. The section "Primary Window Components" in Microsoft Windows User Experience doesn't show anything other than left-justified text, so I think that (at least for Roman script) it should always be displayed to the left. What do you think? Do you have any example of a non-left-justified window title?`

**Comment by xx1182** [comment]
> Hey @xx1182, this is the comment I left on the PR that's linked to this issue. I was wondering if you could help figure out whether this is in-scope for this repo.
> 
> > Hi! I'm wondering if there's a precedent for centered text in Windows 98. The section "Primary Window Components" in Microsoft Windows User Experience doesn't show anything other than left-justified text, so I think that (at least for Roman script) it should always be displayed to the left. What do you think? Do you have any example of a non-left-justified window title?

Technically yes, because it's not "Microsoft related", some developers did/could, don't have any source material, if maybe

>Launch game
>Is centered because it looks cool.

Think of a 90's nerd teenager, with "edgy black background that makes you go blind on those old monitors"

**Comment by juanigaray** [comment]
I can absolutely see why it would look cool. Take a look at the PR if you want to use that selector in your own codebase! s for the issue itself I lean towards thinking it's off scope for this project. Closing this as not planned, please tag me if you find any real world Windows 98 examples!
