### ISSUE TITLE
Inauthentic rendering of top/left window borders

### ISSUE THREAD

**Issue by rhetorica** [jdan/98.css#17]
Hi. The Chicago rendering theme introduced in Windows 95 actually has a fairly prominent mistake in it that your recreation is missing; specifically, window borders (and only window borders) have the "Light" and "Hilight" colours swapped. I've attached some comparative screenshots for reference. You can check [ToastyTech](http://toastytech.com/guis/win98.html) for more exact metrics, e.g. fixing the padding on the window caption text and the caption bar context buttons.

![98css](https://user-images.githubusercontent.com/1402634/79973445-908dd900-8465-11ea-87db-007be9757f89.png)

**Comment by jdan** [comment]
Wow nice catch! Thanks for filing
