### ISSUE TITLE
I create a minesweeper game based on 98.css

### ISSUE THREAD

**Issue by zerosoul** [jdan/98.css#171]
https://ohminesweeper.online/
thanks, great work!

**Comment by zerosoul** [comment]
![image](https://github.com/jdan/98.css/assets/2985895/f503d3a0-3fd9-4b23-af3b-01b42133cdb3)

**Comment by juanigaray** [comment]
That's very cool! Love that you added interaction to other buttons apart from the essentials.

I must ask though, why is this an issue?

**Comment by zerosoul** [comment]
> That's very cool! Love that you added interaction to other buttons apart from the essentials.
> 
> I must ask though, why is this an issue?

because I can only provide public feedback to the author of 98.css here 😂

**Comment by juanigaray** [comment]
Oh! In that case please repost it [here](https://github.com/jdan/98.css/discussions/categories/show-and-tell), I'll close the issue because I'm trying to clean the backlog a little.
