### ISSUE TITLE
TableView JS logic is broken in demo site

### ISSUE THREAD

**Issue by jruales** [jdan/98.css#172]
**Repro:**
1. Go to the demo site, under the TableView section: https://jdan.github.io/98.css/#table-view
2. Click on any cell of the table view
3. Notice that an error appears in the console each time you click on the table:
![image](https://github.com/jdan/98.css/assets/1588988/8635c3aa-9758-41aa-b8ed-61011e588d01)

**Comment by juanigaray** [comment]
Indeed. `Event.path` has been deprecated and removed from Chromium since January of this year. We should use `event.composedPath()`

**Comment by juanigaray** [comment]
Implemented a fix, let me know what you think!
