### ISSUE TITLE
Will there ever be a progress bar?

### ISSUE THREAD

**Issue by TrudeEH** [jdan/98.css#173]
Hello. I love the project, and I was wondering if there are any plans to add a progress bar to 98.css. 7.css has it, and it's quite good.

Thank you.

**Comment by TrudeEH** [comment]
I'm sorry, I didn't realize that there's a PR with a progress bar implementation. I still wonder if it is planned to be merged, however.

Thank you.

**Comment by juanigaray** [comment]
Hi! I'm the one who created [the latest PR for the Progress indicator](https://github.com/jdan/98.css/pull/170). I promise you I'm on it! I want to make sure some other eyes see the implementation before I merge, so your code review is very much welcome. I'm closing this issue, but if you have a review I'll see you there!
