### ISSUE TITLE
Progressbar missing

### ISSUE THREAD

**Issue by bmuessig** [jdan/98.css#18]
The stylesheet looks amazing, but it still lacks the ProgressBar control.
It would be nice to see it added.

**Comment by jdan** [comment]
Great idea!

**Comment by PedroBoni** [comment]
I created a simple class that solves this

**Comment by PedroBoni** [comment]
```html
<div class="meter">
        <span style="width: 80%"></span>
</div>
```
I will do a PR.

**Comment by PedroBoni** [comment]
#96

**Comment by metropolis-nostalgia** [comment]
It not working.
I tried to make a window with 3 different way to show a progress bar:
`<div id="Test" class="window glass" style="width: 300px;">
  <div class="title-bar">
    <div class="title-bar-text">Test</div>
    <div class="title-bar-controls">
      <button aria-label="Minimize"></button>
      <button aria-label="Maximize"></button>
      <button aria-label="Close"></button>
    </div>
  </div>
  <div class="window-body">
	
	
	
	<div class="meter"> 
		<span style="width: 80%"></span> 
	</div>
	
	<div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="80">
		<div style="width: 80%"></div>
	</div>
	
	<progress class="progress-bar-block" value="50" max="100"></progress>

  </div>
</div>`
The result: 
![98progressbar](https://user-images.githubusercontent.com/82685767/115166376-d41f2100-a080-11eb-804d-2d0926cd052c.png)
(I'm using Edge.)
