### ISSUE TITLE
Add support for input type "search"

### ISSUE THREAD

**Issue by agustinl** [jdan/98.css#183]
PR created https://github.com/jdan/98.css/pull/182

![image](https://github.com/jdan/98.css/assets/6640773/dfc8ac9a-9209-419d-9d0d-7115d5c8f15e)

**Comment by pragyamishra56** [comment]
@agustinl Sir could you please assign me this issue it would be my first contributions

**Comment by juanigaray** [comment]
Hi! :wave: do you think it's possible to remove the X to the right so that the search box looks like the W98 text box? Or do you have any examples of W98 search boxes with an X?
