### ISSUE TITLE
Not deploying, error in build/98.css

### ISSUE THREAD

**Issue by ddayan0** [jdan/98.css#28]
When attempting to deploy my app made with React with 98.css, it presents an error message:

./node_modules/98.css/build/98.css
ParserError: Syntax Error at line: 1, column 6
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)

and refuses to compile! Reinstalling 98.css with npm and updating the packages along with reconfiguring my packages.json(https://blog.usejournal.com/how-to-deploy-your-react-app-into-github-pages-b2c96292b18e) does not aid the problem. This has been a consistent issue I have been encountering and is preventing me from further developing my personal website.

**Comment by jdan** [comment]
Hey @ddayan0, sorry this is happening! Could you share a little more about your app? Maybe upload some of it to codesandbox? Using 98.css should be as simple as adding it to `package.json` and `import`ing it with webpack's css-loader + style-loader.

https://codesandbox.io/s/objective-chandrasekhar-t5t6h

**Comment by ddayan0** [comment]
Hey @jdan, thanks for the response. My app is hosted on my github under "personal-website" so you can inspect it there. It is a simple React app with two components containing two windows that is called in a Main.js file. I updated all the packages and checked the internal 98.css files to no avail.  98.css is present in my packages.json and imported properly according to the codesandbox link you shared.

**Comment by jdan** [comment]
Oof, sorry about this one - that was annoying to debug!

Looks like `yarn build` was unhappy with the `:root` rule at the top of the file. I added some code that minifies our build (but includes a source map) so the `:root` is compiled away. 

Wanna update to the latest version (`npm i 98.css@0.1.5`) and give this another whirl?
