### ISSUE TITLE
Buttons need border-radius: 0 for hard rectangle edge

### ISSUE THREAD

**Issue by rogerclark** [jdan/98.css#3]
The Windows Classic style UIs don't have rounded rectangles. On at least Chrome and Edge Preview, you need border-radius: 0 to achieve the hard edges.

**Comment by jdan** [comment]
Thanks for reporting! Mind including a screenshot?

**Comment by pluma** [comment]
Default:
![image](https://user-images.githubusercontent.com/1280922/79963284-76fe8880-8489-11ea-98c9-59bf82da1552.png)

With radius zero:
![image](https://user-images.githubusercontent.com/1280922/79963313-81208700-8489-11ea-8ed1-27cbabe9b354.png)

**Comment by jdan** [comment]
Awesome, thank ya! Will leave this one open if anyone's keen on sending a PR.

**Comment by jdan** [comment]
Fixed via #22
