### ISSUE TITLE
Text Boxes have rounded corners on iOS Google Chrome

### ISSUE THREAD

**Issue by TheBox193** [jdan/98.css#30]
# Description
TextBox has rounded corners when viewing on iOS using Google Chrome.

Might be fixed by #3 

# Screenshot
![image](https://user-images.githubusercontent.com/220755/80025239-ed10e880-84a5-11ea-9022-6a3416fb7a58.png)

**Comment by jdan** [comment]
#22 fixed that, so this is a new bug :) Thanks for filing.

**Comment by jdan** [comment]
Closed via #31 :)
