### ISSUE TITLE
Checkbox/radio label should not be selectable

### ISSUE THREAD

**Issue by ddsol** [jdan/98.css#36]
You should not be able to select certain text, like the checkbox or radio label or other labels.

**Comment by snoopdouglas** [comment]
To expand upon this: as I recall, text in 9x wasn't selectable at all in most cases - so it may be a matter of whitelisting text-selectable controls.

As such, might it be worth applying `user-select: none` to `*`, then overriding where necessary?

**Comment by jdan** [comment]
I closed this in #23 with the idea being that I'm very cautious of preventing selection on the web in library code, and would prefer if end users added them themselves in CSS.

Feel free to add any comments there but I'm going to close this as a dupe.
