### ISSUE TITLE
Slider control

### ISSUE THREAD

**Issue by hedgehog-online** [jdan/98.css#37]
It would be really nice to have a themed slider control component.

![image](https://user-images.githubusercontent.com/55303721/80050482-a75d2a00-8550-11ea-8807-8b7f54e4ca38.png)

https://flylib.com/books/en/4.348.1.74/1/

**Comment by JessFairbairn** [comment]
I'm going to attempt this :)

**Comment by JessFairbairn** [comment]
This is now addressed by version 0.1.14 and can be closed? https://jdan.github.io/98.css/#slider

**Comment by jdan** [comment]
Yep! Good catch, Fixed via #78
