### ISSUE TITLE
Firefox draws its own focus rectangle, which surrounds only the button text

### ISSUE THREAD

**Issue by jroessel** [jdan/98.css#4]
![image](https://user-images.githubusercontent.com/29534431/79946035-76f18f00-846f-11ea-9663-e0599cbe5383.png)

This conflicts with the custom one. [Seems to need](https://stackoverflow.com/a/199319/73070)

```
button::-moz-focus-inner {
  border: 0;
}
```

**Comment by jdan** [comment]
😱 thanks! Wanna send me a PR?
