### ISSUE TITLE
Labels for checkboxes and radio buttons should not be selectable

### ISSUE THREAD

**Issue by kennethsinder** [jdan/98.css#47]
I may be mistaken, but clicking and dragging on labels of a checkbox shouldn't highlight the selected text in blue. If this is the case, and it wouldn't negatively hamper a11y to do so, it seems like the fix is: https://stackoverflow.com/questions/924916/is-there-a-way-to-make-a-div-unselectable?

![image](https://user-images.githubusercontent.com/13790130/80155048-d1cdd800-858e-11ea-91f8-98f91b7d07ae.png)

Feel free to close this issue if either of my two assumptions above (98 components have un-selectable checkbox/radio labels, and making it unselectable wouldn't damage accessibility somehow) is false, but this was just a thought. I'm happy to take this on myself if nobody else grabs it.

**Comment by jdan** [comment]
Hey! Addressed in #23 but feel free to add thoughts there.
