### ISSUE TITLE
missing input type=number styling :)

### ISSUE THREAD

**Issue by nadako** [jdan/98.css#66]
Subj. I _think_ it was called "spin boxes" in Windows 98?

**Comment by jdan** [comment]
Great catch!

**Comment by PedroBoni** [comment]
Could you attach a sample image? 
I never really used windows 98 😬

**Comment by DannyJJK** [comment]
With some googling I got this:
![imagen](https://user-images.githubusercontent.com/11057501/120551768-4f008900-c3ee-11eb-8897-f0f590733d5b.png)

**Comment by Andreymazepas** [comment]
The input can be styled, however the spinner buttons seems to only be customizable on webkit browsers, and to a limit extent. I'll be giving it a shot

**Comment by hello-smile6** [comment]
> Could you attach a sample image? I never really used windows 98 😬

https://copy.sh/v86/?profile=windows98
