### ISSUE TITLE
Slightly different font weight for elements of a tree in tree view if there is more than one word

### ISSUE THREAD

**Issue by jdegrand** [jdan/98.css#68]
Not sure if this was intended or not, but in a tree if there is an element with more than one word it appears slightly bolder than one with a single word.

<img width="183" alt="spaces" src="https://user-images.githubusercontent.com/33506282/80320519-e60b1280-87e4-11ea-9bd3-7a0cc5c9ee3a.png">

**Comment by phaberest** [comment]
Weird, in the docs there is an option that has more words and looks normal.

Are you sure the html structure is correct?
![Screenshot 2020-04-27 at 11 04 56](https://user-images.githubusercontent.com/3464092/80354495-1bf8d700-8877-11ea-953d-5eed553fa6be.jpg)

**Comment by JuanGaray93** [comment]
> Not sure if this was intended or not, but in a tree if there is an element with more than one word it appears slightly bolder than one with a single word.
> 
> <img alt="spaces" width="183" src="https://user-images.githubusercontent.com/33506282/80320519-e60b1280-87e4-11ea-9bd3-7a0cc5c9ee3a.png">

Could you give more details about the browser you're using, your screen resolution, etc?

**Comment by jdegrand** [comment]
My screen resolution is 2560 x 1600. I'm using Safari on macOS Catalina. It appears to be a Safari issue, as I am not seeing it on Google Chrome. I don't think HTML structure is the problem, as it also appears that way on the documentation. Probably just a weird Safari glitch.

<img width="202" alt="98" src="https://user-images.githubusercontent.com/33506282/80390426-662f8780-887a-11ea-9cc7-21b791f8f419.png">

**Comment by jdan** [comment]
Yeah, weird one! Lemme roll this into #13 as a dupe :)
