### ISSUE TITLE
Semantic elements

### ISSUE THREAD

**Issue by piranna** [jdan/98.css#71]
I've seen windows are created with `div` elements, wouldn't it be better to user `header`, `article`, `footer` and other similar ones to identify each section?

**Comment by jdan** [comment]
I'd happily accept a PR to change it `.title-bar, header.title-bar` (I don't wanna introduce a breaking change) but I didn't _really_ consider the top menu to be a "header"

**Comment by piranna** [comment]
The statusbar, definitely is a footer :-)

**Comment by jdan** [comment]
Feel free to leave a comment to that effect in #46
