### ISSUE TITLE
Border for images or other components

### ISSUE THREAD

**Issue by ahota** [jdan/98.css#73]
I'm not sure what to call this, but some windows would have an inset border for images or other components, similar to text areas. Here are a couple screenshots:

The test area in the bottom right:
![image](https://user-images.githubusercontent.com/8506621/80532752-38be0900-8962-11ea-9b8e-c42dffe377bf.png)

The image in the window behind the menus:
![image](https://user-images.githubusercontent.com/8506621/80532903-6b680180-8962-11ea-831a-be529262b07f.png)

This inset border is used for most windows that contain other items, like the file explorer or browser (also seen in the second image). Note that this is different from the Group Box border. It's actually the inverse of the regular window border; the highlight is bottom-right and shadow is top-left, since it's inset.

**Comment by jdan** [comment]
This is a great idea! Any thoughts on what a semantic tag name for this might be? (Is it a `figure`?)

We could definitely add an `.inset` or something but I always prefer to go with tag names if possible.
