### ISSUE TITLE
Duplicated checkbox and radios on PaleMoon

### ISSUE THREAD

**Issue by em92** [jdan/98.css#76]
Hi! Nice css!

Here are some duplicates from https://jdan.github.io/98.css/:
http://i.imgur.com/2uUluIv.png
http://i.imgur.com/o3kHimb.png

PaleMoon 28.9.1

**Comment by jdan** [comment]
It looks like PaleMoon is not respecting `-moz-appearance: none` which may be a bug on their end?

![image](https://user-images.githubusercontent.com/287268/80812957-0b0dd580-8b97-11ea-900c-6b8c2b34bba7.png)

Many of the examples in https://code-boxx.com/simple-pure-css-custom-checkbox/ work in this browser as well.

If I add `display: none` to the element it breaks accessibility, which is a no-go unfortunately.

**Comment by jdan** [comment]
@Lootyhoof unfortunately `display: none` breaks accessibility for these controls so I had to shy away from that

58ae88c adds `position: fixed` and `opacity: 0` as a stopgap here, but for the record `appearance: none` is enough to hide the thing in chrome, mobile safari, and firefox 75. I am unsure where in the spec it's determined that radios/checkboxes should be hidden as well.

@em92 thanks for reporting, wanna give this another whirl?

**Comment by em92** [comment]
@jdan checked again. It is fixed.
Thank you!
