### ISSUE TITLE
License

### ISSUE THREAD

**Issue by antoinerousseau** [jdan/98.css#81]
The license content suggests a copyright, but the repo license is MIT.

https://github.com/jdan/98.css/blob/master/LICENSE

What's the license in the end?

**Comment by jdan** [comment]
MIT!

https://opensource.org/licenses/MIT

**Comment by antoinerousseau** [comment]
Please update or remove the LICENSE file then. And thanks for sharing! :)

**Comment by jdan** [comment]
How should I update it? I posted the MIT license template.

**Comment by antoinerousseau** [comment]
Yes sorry I edited my comment, my bad!

**Comment by jdan** [comment]
No worries :)
