### ISSUE TITLE
Border of groupboxes

### ISSUE THREAD

**Issue by fakekawaii** [jdan/98.css#85]
GroupBoxes are 2 colored (white and dark gray) in w98, however the css has them colored in 4 colors (black, d gray, b gray, white) 
example in windows 98:
![image](https://user-images.githubusercontent.com/52917457/82128046-22180e80-97b8-11ea-9b31-4d7f622e3ba9.png)
css:
![image](https://user-images.githubusercontent.com/52917457/82128051-33f9b180-97b8-11ea-9a26-0bbbe941458b.png)

**Comment by jdan** [comment]
Great catch!

**Comment by nemo369** [comment]
I made a PR for this one
[https://github.com/jdan/98.css/pull/95](https://github.com/jdan/98.css/pull/95)

**Comment by jdan** [comment]
Fixed via #95 (thanks @nemo369 ✨)
