### ISSUE TITLE
Window title bar dimensions seem to be incorrect

### ISSUE THREAD

**Issue by hedgehog-online** [jdan/98.css#9]
It appears that the buttons on the title bar and the borders are not quite the same as on actual Windows 98.

Please compare (grey background is 98.css, teal is Windows 98):
![image](https://user-images.githubusercontent.com/55303721/79955995-7df1bf00-84ba-11ea-9e0e-e82d6c65a13f.png) - 98.css
![image](https://user-images.githubusercontent.com/55303721/79956013-8518cd00-84ba-11ea-826e-a442b5cdb748.png) - Windows 98
![image](https://user-images.githubusercontent.com/55303721/79956067-98c43380-84ba-11ea-98f6-2b5d1354d806.png) - overlaid and centered on the top right corner 
![image](https://user-images.githubusercontent.com/55303721/79956115-a8dc1300-84ba-11ea-9140-8723192769a6.png) - centered on the close button

**Comment by jdan** [comment]
Great screenshots :) Yeah I was moving these around a lot, buttons used to have a combination of inset and outer box shadows, so the width and heights were being nudged up and down 1px at a time. I didn't keep these up with the changes. It's very likely one just needs to add a px or two.

**Comment by vandanmshah** [comment]
Hey, @jdan I would like to pick this issue... Are you on this?

**Comment by jdan** [comment]
@vandanmshah Nope! All you :)
